### ISSUE TITLE
Taking image as frame

### ISSUE THREAD

**Issue by Hilal-Urun** [lukun199/TBEFN#1]
Hi, I want to ask that how can I modify according to real time scenarios for example I want to give each frame for enhancement, I tried to modify code but I get error like;
 [ WARN:0] global C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-1y7gm6kn\opencv\modules\videoio\src\cap_msmf.cpp (438) `anonymous-namespace'::SourceReaderCB::~SourceReaderCB terminating async callback

**Comment by lukun199** [comment]
My apologies for the late reply. It seems that this error is caused by reading a pictrue from cv2. However, to the best of my knowledge, the uploaded code should work properly in most platforms. May you first check if this is caused by TBEFN, or provide more details on this error, say, how to reproduce it? 
I have searched this error and found some related cases, hope the following answers from [stackoverflow](https://stackoverflow.com/questions/60007427/cv2-warn0-global-cap-msmf-cpp-674-sourcereadercbsourcereadercb-termina)  and [opencv](https://answers.opencv.org/question/234996/cap_msmfcpp-435-warn0-on-cv2videocapture-break/) could help.
By the way, the uploaded code performs enhancement for a single image/frame each time; you can also speeds up the inference by stacking frames with the same size into a batch.
Hope this answer useful.

**Comment by Hilal-Urun** [comment]
okey I got it thanks a lot for your response
